sudo: required
language: node_js
cache: yarn
node_js:
  - 8
  - 9
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn test
